version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: gfh-paperless-ai_1
      APP_PORT: 3000
    
  server:
    image: clusterzx/paperless-ai:latest
    user: "1000:1000"
    init: true
